### PR TITLE
Override build parameters

### PR DESCRIPTION
**Pull request by burtlo**
This is not really the best implementation of providing support for overriding and providing additional build commands, but it does the job.

### CODE REVIEW

**Comment by rayh** [comment]
Hi, thanks for the request.  I like the feature, but I'm a bit concerned about making assumptions of the format of the string being appended to cmd.  I'll see if I can rejig it so that BuildCommand maintains a structured representation of the command line args and we just assemble them at the last minute.

**Comment by burtlo** [comment]
Trash it. I think there are better ways that it could have been done.

**Comment by burtlo** [comment]
I would rather use something like the following:

``` ruby
builder.build do |command|
  command.set_parameter('key','value') # adds or replaces -key value
  command.set_environment('KEY','VALUE') #adds or replaces KEY=VALUE
end
```

But again, there are other things that I have in the fire, namely some larger changes that I would I will address in a future pull request.

**Comment by burtlo** [comment]
Opened a different pull request with the content that I am alluding.

**Pull request closed without merging**
