### PR TITLE
Set provisioning profile name to builder, but not path to it.

### PR DESCRIPTION
**Pull request by IvanUshakov**
I'm not found how to add pull request to existing issues. Fix for #62

### CODE REVIEW

**Comment by rayh** [comment]
Rather than making a decision based on a new property, profile_path, i think it would be better to expose @profile as a property, and allow the user to find and assign a profile via installed_profiles.  (I think you started on this path in #62).  

So, how about updating the setter for @profile to map a string path into an instance of ProvisioningProfile.  Then internally, it is expected to be either nil or an instance of ProvisioningProfile.  A couple of places will need to be updated to get the path from the profile when building the xcodebuild command.

This way, we dont need to introduce new properties with similar meanings, and we get to support existing implementations.

**Comment by IvanUshakov** [comment]
ok, I will try do it. But I'm not sure, that can done. I'am not ruby developer

**Comment by IvanUshakov** [comment]
@rayh did you mean this way? Or add setter to @profile property and in it check type? If second, we should determine installed and not installed profiles. And I think, we can do it only by path to it

**Comment by rayh** [comment]
I was thinking that profile=() method would accept a string (i.e. a path)
or a ProvisioningProfile instance.  If it's a string, it simply tries to
instantiate a ProvisioningProfile with that path.

Once we have an actual ProvisioningProfile instance, we should call
install() on it to make sure its available to xcodebuild

On 26 April 2013 22:17, Ivan Ushakov notifications@github.com wrote:

> @rayh https://github.com/rayh did you mean this way? Or add setter to
> @profile https://github.com/profile property and in it check type? If
> second, we should determine installed and not installed profiles. And I
> think, we can do it only by path to it
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/rayh/xcoder/pull/63#issuecomment-17071391
> .

## 

Ray Hilton

## (maker of mobile apps)

13/243 Collins St, Melbourne VIC 3000  |  +61 (0) 430 484 708  |
http://ray.sh

**Comment by IvanUshakov** [comment]
ok, thanks for the answer

**Comment by xslim** [comment]
I've made a small test not to have race condition https://github.com/rayh/xcoder/pull/65

**Comment by IvanUshakov** [comment]
@rayh, can you review PR?

**Comment by IvanUshakov** [comment]
@rayh, what i should do now? close this one, or rebase on top of master? I think some changes from this PR would be useful

**Comment by rayh** [comment]
Can you rebase so I can see what the diff is...  Does the other PR cover
some of your concern?

On 21/05/2013, at 18:11, Ivan Ushakov notifications@github.com wrote:

@rayh https://github.com/rayh, what i should do now? close this one, or
rebase on top of master? I think some changes from this PR would be useful

—
Reply to this email directly or view it on
GitHubhttps://github.com/rayh/xcoder/pull/63#issuecomment-18194695
.

**Comment by IvanUshakov** [comment]
done

**Pull request merged**
