### PR TITLE
Prefer file paths over file names when looking up existing buildfiles

### PR DESCRIPTION
**Pull request by torarnv**
Otherwise there's no way to add two build files with the same name, but different paths, to the same build phase.

### CODE REVIEW

**Comment by torarnv** [comment]
Thanks! Would you mind tagging and publishing a 0.1.13 release of the gem? Or is there a way I can set up my gemspec to rely on master of xcoder?

**Comment by rayh** [comment]
I believe you can do:

gem 'xcoder', :git => 'https://github.com/rayh/xcoder.git'

but, I will do another release soon... have some other bits to clean up as
well

On 7 September 2012 19:54, Tor Arne Vestbø notifications@github.com wrote:

> Thanks! Would you mind tagging and publishing a 0.1.13 release of the gem?
> Or is there a way I can set up my gemspec to rely on master of xcoder?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/rayh/xcoder/pull/49#issuecomment-8360996.

## 

## Ray Hilton

a: 13/243 Collins Street, Melbourne VIC 3000
m: 0430 484 708
w: http://rayh.com.au

**Comment by torarnv** [comment]
Friendly ping on a 0.1.13 release :smile: 

I couldn't find a way to use bundler to allow people to pull down my gem and get HEAD of your repo as a depend.

**Comment by rayh** [comment]
Sorry about that.  I've pushed a 0.1.13 release.

On 16 October 2012 04:35, Tor Arne Vestbø notifications@github.com wrote:

> Friendly ping on a 0.1.13 release [image: :smile:]
> 
> I couldn't find a way to use bundler to allow people to pull down my gem
> and get HEAD of your repo as a depend.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/rayh/xcoder/pull/49#issuecomment-9453983.

## 

## Ray Hilton

a: 13/243 Collins Street, Melbourne VIC 3000
m: 0430 484 708
w: http://rayh.com.au

**Comment by torarnv** [comment]
Awesome, thanks!

**Pull request merged**
