### PR TITLE
Resources

### PR DESCRIPTION
**Pull request by burtlo**
This is the initial work to provide more flexibility and extendability to the project parsing system by introducing the concept of the `Xcode::Resource` which is a fancy wrapper for the dictionary of properties. I attempted to document and test a large number of these changes.

A large number of the classes, like Target and Configuration, are now gone and instead are modules. These modules are mixed into the generic `Resource` when the `isa` property value string matches a module defined in the `Registry`.

Ultimately, at this stage of the code, you can:
- Traverse groups
- Add sub-groups
- Add files
- Add frameworks
- Add configuration values
- Save the project

I have some further work that I am exploring that adds the ability to create targets, configuration lists, configurations, and the other requirements. It's all still rough, but I'm pretty excited about the potential to manipulate Xcode project files to generate legitimate installers for code.

You are welcome to ignore the pull request and not merge it in if it is not what you are looking to accomplish with the gem.

### CODE REVIEW

**Comment by rayh** [comment]
Woa, this is quite a substantial merge.  I'll try and do my best to get it in as it sounds like it is a Good Thing in general.  So, I assume that from the front end's point of view, things remain more or less that same?  (i.e. enumerating workspaces, projects, targets, schemes and configs)?

Also, do you think this would provide a solid basis on which to provide write functionality?  I had previously spoken to keithpitt about moving some of his vendorkit project manipulation code into xcoder

**Comment by burtlo** [comment]
First, let me say: Wow! I didn't know about vendorkit. That is exactly where I was heading with the code that I was writing into Xcoder. From first glance it seems that the solution that I arrived at is similar.

Second, and more importantly, all the original functionality has still been preserved. You are still able to enumerate existing projects, targets, and configs. All the work that I have done is how that they are arranged and for the most part that is not too drastically different.

The real key to understanding the implementation is the `Registry` module and the `Resource` module. Every object within the project is a `Resource` and every property in the hash of properties generates methods equal to the key names. In most cases the values are simply returned, but in the cases of the special identifiers, 24 Length hexadecimal strings, if any of those are every returned instead the system does a look up in the `Registry` to return the `Resource` object.

The second fun thing is that each Resource, based on the `isa` property will have additional module mixed in them. This makes the code flexible to changes by Apple, supporting new formats, and divides the functionality into their specific types without any strangeness that comes from sub-classing.

I have write functionality completed in commits on the following branch: https://github.com/burtlo/xcoder/tree/create-targets

**Comment by rayh** [comment]
That's pretty impressive stuff!

I'll try and get my head around it tonight and give merging a go.
Thanks for the detail, I think it sounds like a much better approach

On 10/02/2012, at 17:29, Franklin Webber
reply@reply.github.com
wrote:

**Comment by burtlo** [comment]
Found that the impressive code around the resources should have been using `extend` with the found module and not `class_eval`ing it all into Resource. I fixed that and the other errors that appeared because the other build phases were missing from the Registry list.

**Comment by burtlo** [comment]
I think a good way to see the awesomeness of what is going on here is to use IRB and traverse the objects within the project:

``` ruby

> project.targets.first

 => PBXNativeTarget 7165D44F146B4EA100DE2F0E {"buildConfigurationList"=>"7165D47D146B4EA100DE2F0E", "productReference"=>"7165D450146B4EA100DE2F0E", "productType"=>"com.apple.product-type.application", "productName"=>"TestProject", "isa"=>"PBXNativeTarget", "buildPhases"=>["7165D44C146B4EA100DE2F0E", "7165D44D146B4EA100DE2F0E", "7165D44E146B4EA100DE2F0E"], "dependencies"=>[], "name"=>"TestProject", "buildRules"=>[]} 

> project.targets.first.buildPhases

=> [PBXSourcesBuildPhase 7165D44C146B4EA100DE2F0E {"isa"=>"PBXSourcesBuildPhase", "buildActionMask"=>"2147483647", "files"=>["7165D461146B4EA100DE2F0E", "7165D465146B4EA100DE2F0E", "97C80BE5BF3C7AE5C68D7F71"], "runOnlyForDeploymentPostprocessing"=>"0"}, PBXFrameworksBuildPhase 7165D44D146B4EA100DE2F0E {"isa"=>"PBXFrameworksBuildPhase", "buildActionMask"=>"2147483647", "files"=>["7165D455146B4EA100DE2F0E", "7165D457146B4EA100DE2F0E", "7165D459146B4EA100DE2F0E"], "runOnlyForDeploymentPostprocessing"=>"0"}, PBXResourcesBuildPhase 7165D44E146B4EA100DE2F0E {"isa"=>"PBXResourcesBuildPhase", "buildActionMask"=>"2147483647", "files"=>["7165D45F146B4EA100DE2F0E"], "runOnlyForDeploymentPostprocessing"=>"0"}] 

 > project.targets.first.buildPhases.first.files.first

=> PBXBuildFile 7165D461146B4EA100DE2F0E {"isa"=>"PBXBuildFile", "fileRef"=>"7165D460146B4EA100DE2F0E"}

> project.targets.first.buildPhases.first.files.first.fileRef

=> PBXFileReference 7165D460146B4EA100DE2F0E {"path"=>"main.m", "isa"=>"PBXFileReference", "lastKnownFileType"=>"sourcecode.c.objc", "sourceTree"=>"<group>"} 
```

This is using none of the convenience methods that I added, similar to the `target(name)` or `config(name)` methods that you created and what you get is objects all the way through without any messy code that needs to traverse the hash to build an object tree. Here I walked from the project all the way to a file, through the target's build phase reference to it through the build file.

**Comment by rayh** [comment]
I've tried to merge, but I'm getting an error:

```
undefined method `project=' for #<Xcode::Resource:0x007f9b5338db00>
```

Now, I can see whats /supposed/ to happen, the Xcode::Target module
gets included and that defines an attr_accessor for :project.  If I
debug the initialize() method for Resource, I can see that it picks up
the correct isa and maps it to Xcode::Target.  It then calls
self.extend, and that doesn't cause any errors, yet I cannot set that
property.

Any ideas?

On 10 February 2012 20:07, Franklin Webber
reply@reply.github.com
wrote:

> I think a good way to see the awesomeness of what is going on here is to use IRB and traverse the objects within the project:
> 
> ``` ruby
> 
> > project.targets.first
> 
>  => PBXNativeTarget 7165D44F146B4EA100DE2F0E {"buildConfigurationList"=>"7165D47D146B4EA100DE2F0E", "productReference"=>"7165D450146B4EA100DE2F0E", "productType"=>"com.apple.product-type.application", "productName"=>"TestProject", "isa"=>"PBXNativeTarget", "buildPhases"=>["7165D44C146B4EA100DE2F0E", "7165D44D146B4EA100DE2F0E", "7165D44E146B4EA100DE2F0E"], "dependencies"=>[], "name"=>"TestProject", "buildRules"=>[]}
> 
> > project.targets.first.buildPhases
> 
> => [PBXSourcesBuildPhase 7165D44C146B4EA100DE2F0E {"isa"=>"PBXSourcesBuildPhase", "buildActionMask"=>"2147483647", "files"=>["7165D461146B4EA100DE2F0E", "7165D465146B4EA100DE2F0E", "97C80BE5BF3C7AE5C68D7F71"], "runOnlyForDeploymentPostprocessing"=>"0"}, PBXFrameworksBuildPhase 7165D44D146B4EA100DE2F0E {"isa"=>"PBXFrameworksBuildPhase", "buildActionMask"=>"2147483647", "files"=>["7165D455146B4EA100DE2F0E", "7165D457146B4EA100DE2F0E", "7165D459146B4EA100DE2F0E"], "runOnlyForDeploymentPostprocessing"=>"0"}, PBXResourcesBuildPhase 7165D44E146B4EA100DE2F0E {"isa"=>"PBXResourcesBuildPhase", "buildActionMask"=>"2147483647", "files"=>["7165D45F146B4EA100DE2F0E"], "runOnlyForDeploymentPostprocessing"=>"0"}]
> 
>  > project.targets.first.buildPhases.first.files.first
> 
> => PBXBuildFile 7165D461146B4EA100DE2F0E {"isa"=>"PBXBuildFile", "fileRef"=>"7165D460146B4EA100DE2F0E"}
> 
> > project.targets.first.buildPhases.first.files.first.fileRef
> 
> => PBXFileReference 7165D460146B4EA100DE2F0E {"path"=>"main.m", "isa"=>"PBXFileReference", "lastKnownFileType"=>"sourcecode.c.objc", "sourceTree"=>"<group>"}
> ```
> 
> This is using none of the convenience methods that I added, similar to the `target(name)` or `config(name)` methods that you created and what you get is objects all the way through without any messy code that needs to traverse the hash to build an object tree. Here I walked from the project all the way to a file, through the target's build phase reference to it through the build file.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/rayh/xcoder/pull/2#issuecomment-3903220

## 

## Ray Hilton

a: 13/243 Collins Street, Melbourne VIC 3000
m: 0430 484 708
w: http://rayh.com.au

**Comment by burtlo** [comment]
I merged it with some conflicts, but it seems to be alright: https://github.com/burtlo/xcoder/commit/131fd602636621046c1fbeb81dc701062c2e788a

There were conflicts around the `project` file related to the changes to the parsing. I had moved all of that out to a Parser class, to separate the concerns for future situations on how we might change the parsing of the Xcode project file.

Running all the tests and interrogating the objects in IRB seem to work.

If you want to push the state of the merged branch up to a different branch here I would love to take a look and see how I can help.

**Comment by rayh** [comment]
Seems to work ok with the example project, but I have another project
that its failing with.  I'll try and see if I can recreate it in a
test.

On 11 February 2012 04:19, Franklin Webber
reply@reply.github.com
wrote:

> I merged it with some conflicts, but it seems to be alright: https://github.com/burtlo/xcoder/commit/131fd602636621046c1fbeb81dc701062c2e788a
> 
> There were conflicts around the `project` file related to the changes to the parsing. I had moved all of that out to a Parser class, to separate the concerns for future situations on how we might change the parsing of the Xcode project file.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/rayh/xcoder/pull/2#issuecomment-3909941

## 

## Ray Hilton

a: 13/243 Collins Street, Melbourne VIC 3000
m: 0430 484 708
w: http://rayh.com.au

**Comment by rayh** [comment]
Seems to be PBXAggregateTarget gets added to @project.targets, and
then it fails when we try to assign project to it, as it has no
module.  I've added a mapping to Target, and it seems to work.  Do you
foresee any problems with that?

On 11 February 2012 13:53, Ray Hilton ray@wirestorm.net wrote:

> Seems to work ok with the example project, but I have another project
> that its failing with.  I'll try and see if I can recreate it in a
> test.
> 
> On 11 February 2012 04:19, Franklin Webber
> reply@reply.github.com
> wrote:
> 
> > I merged it with some conflicts, but it seems to be alright: https://github.com/burtlo/xcoder/commit/131fd602636621046c1fbeb81dc701062c2e788a
> > 
> > There were conflicts around the `project` file related to the changes to the parsing. I had moved all of that out to a Parser class, to separate the concerns for future situations on how we might change the parsing of the Xcode project file.
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/rayh/xcoder/pull/2#issuecomment-3909941
> 
> ## 
> 
> ## Ray Hilton
> 
> a: 13/243 Collins Street, Melbourne VIC 3000
> m: 0430 484 708
> w: http://rayh.com.au

## 

## Ray Hilton

a: 13/243 Collins Street, Melbourne VIC 3000
m: 0430 484 708
w: http://rayh.com.au

**Comment by burtlo** [comment]
Ray, that is perfect. That's the exact purpose of the mappings. Map Xcode project types to the Ruby Functionality. 

Awesome!

**Pull request merged**
